application: xuanji
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.2"

- name: webapp2
  version: "2.5.1"

- name: lxml
  version: latest

handlers:  
- url: /
  static_files: index.html
  upload: index\.html

- url: /echo/.*
  script: echo.app

- url: /pocket/.*
  script: pocket.app

- url: /goodreads/.*
  script: goodreads.app

- url: /python/.*
  script: python.app

- url: /python/css
  static_dir: css

- url: /libgit2-js
  static_dir: libgit2-js

- url: /js-scheme-stk
  static_dir: js-scheme-stk

- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /python/ace
  static_dir: ace

- url: /parallel-text/
  static_dir: parallel-text

- url: /isicp/
  static_files: isicp/index.html
  upload: isicp/index\.html

- url: /isicp
  static_dir: isicp

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: index.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?LICENSE